### ISSUE TITLE
ASan runtime does not come first in initial library list

### ISSUE THREAD

**Issue by FD-** [irajkovic/dotclock#1]
I'm trying to run your code on a Raspberry Pi 3B+ running Raspbian Buster. Unfortunately, it doesn't work. It compiles fine, but running it just yields

````
./clock /dev/spi0.0
==663==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
````

**Comment by irajkovic** [comment]
Hi, I didn't get notification for the issue, so sorry for late response.

Could you try removing `-lasan -fsanitize=address` from the Makefile and recompiling?

**Comment by irajkovic** [comment]
I also added CMake build option and remove these lines, so if you try to rebuild with any of the two options, you should be set.
